# Generated by Django 5.0.6 on 2024-07-06 00:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('next_interval', models.IntegerField(default=5)),
                ('last_send_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
